[package]
name = "dofi"
version = "0.1.3"
edition = "2018"
authors = ["Akatsuki Rui <akiirui@outlook.com>"]
description = "A simple dotfile manager"
license = "MIT"
readme = "README.md"
keywords = ["dotfile"]
documentation = "https://docs.rs/dofi"
homepage = "https://github.com/akiirui/dofi/"
repository = "https://github.com/akiirui/dofi/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
dirs = "4.0"

[profile.release]
lto = true
